In [1]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#only change the shape
a.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [13]:
# it changes the element also
np.resize(a,(4,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 1]])

In [18]:
b = np.array([[[1,2,3] , [3,4,5] , [5,6,7], [7,8,9]]])
b

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]]])

In [20]:
#converts array into 1d and returns copy os array
b.flatten()

array([1, 2, 3, 3, 4, 5, 5, 6, 7, 7, 8, 9])

In [22]:
# it also converts array into 1d but returns copy only when it's needed
b.ravel()

array([1, 2, 3, 3, 4, 5, 5, 6, 7, 7, 8, 9])